"""Generates course recommendations using semantic similarity.

This module provides the `CourseRecommender` class, which leverages
sentence transformers to convert course descriptions into dense vector
embeddings. It then recommends new courses by comparing a user's 
enrolled courses to the course catalog using cosine similarity. It also
supports saving and loading pre-computed embeddings to avoid redundant
processing.

Author: Hassan Darwish
Date: April 2026
"""

import logging
import joblib
import numpy as np
from numpy.typing import NDArray
from typing import List, Optional, Dict, Union
from pathlib import Path
from datetime import datetime
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from course_recommender.src.utils.logger import setup_logging

# Initialize environment and logging
setup_logging()
logger = logging.getLogger(__name__)

class CourseRecommender:
    """A content-based recommender system using semantic text embeddings.

    This class uses a pre-trained transformer model to encode course text 
    into high-dimensional vectors. User profiles are generated by averaging 
    the vectors of their enrolled courses. Recommendations are made by 
    finding the closest course vectors to the user profile in the embedding space.
    
    Attributes:
        model (SentenceTransformer): The embedding model.
        index_list (List[int]): The ordered list of course IDs.
        embeddings (Optional[NDArray[np.float32]]): The matrix of course embeddings.
        _id_to_idx (Dict[int, int]): Internal mapping from course ID to matrix index.
    """

    # --- Constants for model configuration ---
    DEFAULT_MODEL_NAME = 'all-MiniLM-L6-v2'
    """The default HuggingFace model used for text embeddings."""

    MAX_RECOMMENDATIONS = 8
    """The maximum number of course recommendations to return."""

    ERROR_NO_EMBEDDINGS = 'No embeddings were generated. Call generate_embeddings() first.'
    """Error message raised when prediction/saving is attempted before embedding generation."""

    # --- Constants for artifact management ---
    DEFAULT_ARTIFACT_DIR = 'models'
    """Default directory for saving generated embeddings."""
    
    ARTIFACT_EXTENSION = '.joblib'
    """Expected file extension for saved state artifacts."""

    def __init__(self) -> None:
        """Initializes the recommender and loads the embedding model."""
        self.model = SentenceTransformer(self.DEFAULT_MODEL_NAME)
        self.index_list: List[int] = []
        self.embeddings: Optional[NDArray[np.float32]] = None
        
        # Internal mapping to speed up index lookups during prediction
        self._id_to_idx: Dict[int, int] = {}

    def generate_embeddings(self, index_list: List[int], text_list: List[str]) -> None:
        """Generates and stores vector embeddings for the course catalog.

        Args:
            index_list (List[int]): The list of unique course IDs.
            text_list (List[str]): The corresponding list of course texts to encode.
        """
        self.index_list = index_list
        self._id_to_idx = {course_id: idx for idx, course_id in enumerate(self.index_list)}
        
        logger.info(f"Generating embeddings for {len(text_list)} courses...")
        self.embeddings = self.model.encode(text_list)
        logger.info("Embeddings generated successfully.")

    def predict(self, user_enrolled_index_list: List[int]) -> List[int]:
        """Predicts recommended courses based on a user's enrollment history.

        Args:
            user_enrolled_index_list (List[int]): IDs of courses the user is taking.

        Returns:
            List[int]: A list of up to MAX_RECOMMENDATIONS recommended course IDs.

        Raises:
            ValueError: If the model's embeddings have not been generated yet.
        """
        if self.embeddings is None or len(self.index_list) == 0:
            logger.error(self.ERROR_NO_EMBEDDINGS)
            raise ValueError(self.ERROR_NO_EMBEDDINGS)
        
        # Extract vectors using O(1) dictionary lookup
        user_vector: List[NDArray[np.float32]] = []
        for eid in user_enrolled_index_list:
            if eid in self._id_to_idx:
                idx = self._id_to_idx[eid]
                user_vector.append(self.embeddings[idx])
        
        if not user_vector:
            return []
        
        # Mean Pooling to create user profile
        user_profile: NDArray[np.float32] = np.mean(user_vector, axis=0)
        
        # Cosine Similarity calculation
        scores: NDArray[np.float32] = cosine_similarity([user_profile], self.embeddings)[0]
        top_indices: NDArray[np.intp] = np.argsort(scores)[::-1]

        # Filter recommendations using a Set for O(1) exclusion lookups
        recommended_ids: List[int] = []
        enrolled_set = set(user_enrolled_index_list) 

        for idx in top_indices:
            rec_id = self.index_list[idx]
            
            if rec_id not in enrolled_set:
                recommended_ids.append(rec_id)
            
            if len(recommended_ids) >= self.MAX_RECOMMENDATIONS:
                break 
        
        return recommended_ids

    def save_artifact(self, directory: Union[Path, str] = DEFAULT_ARTIFACT_DIR) -> None:
        """Saves the current embeddings and mapping structures to disk.

        Serializes the model state using joblib to avoid recomputing 
        embeddings on future runs.

        Args:
            directory (Union[Path, str]): The directory where the artifact 
                                          will be saved.

        Raises:
            ValueError: If there are no embeddings currently loaded to save.
        """
        if self.embeddings is None:
            logger.error(self.ERROR_NO_EMBEDDINGS)
            raise ValueError(self.ERROR_NO_EMBEDDINGS)
        
        # 1. Ensure the target directory exists
        save_dir = Path(directory)
        save_dir.mkdir(parents=True, exist_ok=True)
        
        # 2. Package the state into a dictionary
        state = {
            "index_list": self.index_list,
            "_id_to_idx": self._id_to_idx,
            "embeddings": self.embeddings
        }
        
        # 3. Construct a dynamic, timestamped filename
        date_stamp = datetime.now().strftime("%Y_%m_%d")
        filename = f'recommender_embeddings_{date_stamp}{self.ARTIFACT_EXTENSION}'
        full_path = save_dir / filename
        
        # 4. Serialize to disk
        joblib.dump(value=state, filename=full_path)
        logger.info(f"Artifact successfully saved to: {full_path}")
    
    def load_artifact(self, file_path: Union[Path, str]) -> None:
        """Loads pre-computed embeddings and mapping structures from disk.

        Args:
            file_path (Union[Path, str]): The full path to the .joblib artifact.

        Raises:
            FileNotFoundError: If the provided path does not exist.
            ValueError: If the file does not have the correct .joblib extension.
        """
        path = Path(file_path)

        # 1. Validate file existence and type
        if not path.exists():
            error_msg = f"Artifact file cannot be found: {path}"
            logger.error(error_msg)
            raise FileNotFoundError(error_msg)
            
        if path.suffix != self.ARTIFACT_EXTENSION:
            error_msg = f"Expected {self.ARTIFACT_EXTENSION} extension, but got {path.suffix}"
            logger.error(error_msg)
            raise ValueError(error_msg)
        
        # 2. Deserialize the dictionary state
        logger.info(f"Loading artifacts from {path}...")
        state = joblib.load(path)
        
        # 3. Safely extract values using dictionary keys
        self.index_list = state.get("index_list", [])
        self._id_to_idx = state.get("_id_to_idx", {})
        self.embeddings = state.get("embeddings", None)
        
        logger.info("Model artifacts loaded successfully.")