"""Data validation models for the Question-Answering API.

This module defines the Pydantic schemas used to strictly validate 
incoming user queries and format the outgoing responses for the 
RAG (Retrieval-Augmented Generation) system.

Author: Hassan Darwish
Date: May 2026
"""

# 1. Standard Library Imports
from typing import Any, Dict, List

# 2. Third-Party Imports
from pydantic import BaseModel, Field


class QARequest(BaseModel):
    """Schema for incoming user questions.
    
    Validates that the query meets basic structural requirements 
    before it consumes system resources (like embedding generation).
    """
    
    question: str = Field(
        ..., 
        min_length=3,
        description="The user's natural language query.",
        json_schema_extra={
            "example": "What are the prerequisites for Advanced Calculus?"
        }
    )


class QAResponse(BaseModel):
    """Schema for the finalized LLM response and its supporting evidence.
    
    Ensures the API always returns a predictable structure, containing 
    both the synthesized answer and the specific document metadata used 
    to ground the LLM's response.
    """
    
    answer: str = Field(
        ...,
        description="The synthesized answer generated by the Large Language Model.",
        json_schema_extra={
            "example": "To enroll in Advanced Calculus, you must first complete Linear Algebra."
        }
    )
    
    source_documents: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Metadata dictionaries representing the vector chunks used as context.",
        json_schema_extra={
            "example": [
                {
                    "document_id": 105, 
                    "source_title": "Mathematics Department Syllabus", 
                    "chunk_index": 4
                }
            ]
        }
    )