"""Provides the LangChain integration for local Ollama models.

This module contains the `OllamaLLM` class, which implements the `BaseLLM` 
contract. It handles the secure initialization and execution of inference 
requests against a locally hosted Ollama server.

Author: Hassan Darwish
Date: May 2026
"""

# 1. Standard Library Imports
import logging

# 2. Third-Party Imports
from langchain_community.llms import Ollama

# 3. Local Application Imports
from study_copilot.app.generation.base_llm import BaseLLM
from study_copilot.app.core.config import get_settings
from study_copilot.app.utils.logger import setup_logging

# Initialize environment, logging, and global settings
setup_logging()
logger = logging.getLogger(__name__)
settings = get_settings()

class OllamaLLM(BaseLLM):
    """Implementation of the BaseLLM contract for local Ollama models.
    
    This class manages the HTTP connection to the Ollama server via LangChain,
    falling back to environment settings if specific overrides aren't provided.
    """

    # --- Constants for Error Handling and Logging ---
    ERROR_EMPTY_PROMPT = "Cannot generate a response for an empty or invalid prompt."
    """Error raised when the system attempts to send a blank query to the LLM."""

    ERROR_INIT_FAILED = "Failed to initialize Ollama LLM at {host}: {error}"
    """Error raised when LangChain fails to bind to the Ollama server."""

    ERROR_GEN_FAILED = "LLM generation failed during inference: {error}"
    """Error raised when the Ollama server crashes or times out during generation."""

    def __init__(
        self, 
        host_override: str | None = None, 
        model_override: str | None = None
    ) -> None:
        """Initializes the connection to the local Ollama server.
        
        Args:
            host_override (str | None): Optional URL to override the default host.
            model_override (str | None): Optional string to override the default model.
            
        Raises:
            RuntimeError: If the LangChain client fails to initialize.
        """
        # 1. Configuration Resolution
        # Leverage Python's short-circuit evaluation (`or`) to prefer overrides
        self.host = host_override or settings.LLM_HOST
        model_name = model_override or settings.LLM_MODEL_NAME
        
        try:
            # 2. Initialize the LangChain Wrapper
            # Explicitly passing base_url ensures it doesn't default to localhost 
            # if you are running Ollama in a separate Docker container.
            self.model = Ollama(
                base_url=self.host,
                model=model_name
            )
            logger.info(f"Initialized Ollama LLM with model '{model_name}' at {self.host}")
            
        except Exception as e:
            error_msg = self.ERROR_INIT_FAILED.format(host=self.host, error=str(e))
            logger.exception(error_msg)
            raise RuntimeError(error_msg)
            
    def generate(self, prompt: str) -> str:
        """Sends the assembled prompt to Ollama and returns the synthesized text.

        Args:
            prompt (str): The fully assembled context and user query.

        Returns:
            str: The raw text response generated by the LLM.

        Raises:
            ValueError: If the input prompt is empty.
            RuntimeError: If the inference request times out or fails.
        """
        # 1. Strict Validation (Fail-Fast)
        if not prompt or not isinstance(prompt, str) or not prompt.strip():
            logger.error(self.ERROR_EMPTY_PROMPT)
            raise ValueError(self.ERROR_EMPTY_PROMPT)

        # 2. Execute Inference
        logger.debug("Valid prompt received. Sending to Ollama for generation...")
        try:
            response: str = self.model.invoke(prompt)
            logger.info("Successfully generated response from Ollama.")
            return response
            
        except Exception as e:
            # 3. Catch and Escalate Network/Inference Errors
            error_msg = self.ERROR_GEN_FAILED.format(error=str(e))
            logger.exception(error_msg)
            raise RuntimeError(error_msg)